<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TeamStatsSeeder extends Seeder
{
    /**
     * Run the team stats seeds.
     */
    public function run(): void
    {
        DB::table('team_stats')->insert([
            'team_id' => 1,
            'matches_played' => 1178,
            'wins' => 639,
            'losses' => 252,
            'saves' => 1119,
            'penalties_saved' => 1,
            'punches' => 50,
            'high_claims' => 77,
            'catches' => 21,
            'throw_outs' => 603,
            'goal_kicks' => 845,
            'clean_sheets' => 447,
            'goals_conceded' => 1173,
            'tackles' => 11915,
            'tackle_success' => 71,
            'blocked_shots' => 2572,
            'interceptions' => 8984,
            'clearances' => 16001,
            'own_goals' => 47,
            'goals' => 2076,
            'penalties_scored' => 73,
            'shots' => 9722,
            'big_chances_created' => 874,
            'hit_woodwork' => 278,
            'passes' => 338431,
            'passes_accuracy' => 84,
            'crosses' => 13481,
            'cross_accuracy' => 21,
            'yellow_cards' => 1778,
            'red_cards' => 102,
            'fouls' => 1982,
            'offsides' => 1400,
        ], [
            'team_id' => 2,
            'matches_played' => 1178,
            'wins' => 621,
            'losses' => 268,
            'saves' => 847,
            'penalties_saved' => 2,
            'punches' => 70,
            'high_claims' => 73,
            'catches' => 25,
            'throw_outs' => 884,
            'goal_kicks' => 863,
            'clean_sheets' => 452,
            'goals_conceded' => 1177,
            'tackles' => 12857,
            'tackle_success' => 72,
            'blocked_shots' => 2806,
            'interceptions' => 7727,
            'clearances' => 15768,
            'own_goals' => 43,
            'goals' => 2068,
            'penalties_scored' => 82,
            'shots' => 10780,
            'big_chances_created' => 912,
            'hit_woodwork' => 300,
            'passes' => 340789,
            'passes_accuracy' => 82,
            'crosses' => 14354,
            'cross_accuracy' => 22,
            'yellow_cards' => 1462,
            'red_cards' => 61,
            'fouls' => 1952,
            'offsides' => 1400,
        ], [
            'team_id' => 3,
            'matches_played' => 988,
            'wins' => 491,
            'losses' => 283,
            'saves' => 715,
            'penalties_saved' => 3,
            'punches' => 52,
            'high_claims' => 92,
            'catches' => 24,
            'throw_outs' => 974,
            'goal_kicks' => 898,
            'clean_sheets' => 343,
            'goals_conceded' => 1093,
            'tackles' => 11657,
            'tackle_success' => 72,
            'blocked_shots' => 2778,
            'interceptions' => 8030,
            'clearances' => 15351,
            'own_goals' => 40,
            'goals' => 1724,
            'penalties_scored' => 91,
            'shots' => 10345,
            'big_chances_created' => 1050,
            'hit_woodwork' => 282,
            'passes' => 354787,
            'passes_accuracy' => 85,
            'crosses' => 13264,
            'cross_accuracy' => 22,
            'yellow_cards' => 1440,
            'red_cards' => 75,
            'fouls' => 1995,
            'offsides' => 1389,
        ], [
            'team_id' => 1,
            'matches_played' => 0,
            'wins' => 0,
            'losses' => 0,
            'saves' => 0,
            'penalties_saved' => 0,
            'punches' => 0,
            'high_claims' => 0,
            'catches' => 0,
            'throw_outs' => 0,
            'goal_kicks' => 0,
            'clean_sheets' => 0,
            'goals_conceded' => 0,
            'tackles' => 0,
            'tackle_success' => 0,
            'blocked_shots' => 0,
            'interceptions' => 0,
            'clearances' => 0,
            'own_goals' => 0,
            'goals' => 0,
            'penalties_scored' => 0,
            'shots' => 0,
            'big_chances_created' => 0,
            'hit_woodwork' => 0,
            'passes' => 0,
            'passes_accuracy' => 0,
            'crosses' => 0,
            'cross_accuracy' => 0,
            'yellow_cards' => 0,
            'red_cards' => 0,
            'fouls' => 0,
            'offsides' => 0,
        ]);
    }
}
